### PR TITLE
1,2 and 5 easy

### PR DESCRIPTION
**Pull request by marquinhos87**
Neste pull coloco a minha solução para o problema 1,2 e 5 easy, coloco ainda o 5 medium mas este não funciona

### CODE REVIEW

**Comment by herulume** [comment]
Thanks!

Could you remove all the documentation, besides the readme?
Also, according to your commit messages some of your solutions do not work, can you confirm that? 

Please don't commit code that doesn't work and rebase all the commits into one.

**Comment by marquinhos87** [comment]
I remove the solution that doesn't work and remove the doc folder

**Comment by marquinhos87** [comment]
> Thanks!
> 
> Could you remove all the documentation, besides the readme?
> Also, according to your commit messages some of your solutions do not work, can you confirm that?
> 
> Please don't commit code that doesn't work and rebase all the commits into one.

How to rebase all commits into one?

**Comment by ZePedroResende** [comment]
Hey just a heads up @marquinhos87, you submited code for code golf but it really  doesn't qualifies as a [codegolf](https://en.wikipedia.org/wiki/Code_golf) .
Maybe change it to a go fast solution (that means for the quickest code possible) :smile: ? 

Could you also remove the install from the make file?  Its a little inconvenient for automatic testing :smile: , thanks ! 

You can read about squash [here](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history) in the squash section :smile:

**Comment by marquinhos87** [comment]
Checkout #20 version

**Pull request closed without merging**
